### ISSUE TITLE
Assign operator vs. Equal to operator ...

### ISSUE THREAD

**Issue by boa2145** [VBAndCs/sVB-Small-Visual-Basic#18]
I would like to use two operators in Small Visual Basic for assignment and equality, like Python and C# do. It is confusing to me that one and the same operator "=" is sometimes used for value assignment and then as a comparison operator for equality. It is much better to use "=" for the value assignment and "==" for equality. Regards ... Gregor

**Comment by VBAndCs** [comment]
@Gregor
Unfortunately, this is not possible, because it is one of the BASIC fundamentals, which makes VB fanatics hate the C syntax :D
`=` is used for assignment in one possible place, as the second token in the line, preceded with an identifier, otherwise it is defiantly the equality operator. For example, in this code:
```
x = 1 
y = x = 2
``` 

x with be set to 1, and y will be set to False, unlike to C syntax, which will set both y and x to 2!

**Comment by boa2145** [comment]
Good morning Mohammad,

okay, I have to respect the Basic fundamentals. I am an old fan of the
Basic programming language. It was an idea, because I study other
languages, too. I have to say that Python is really nearby Basic what
Kemeny and Kurtz said: Basic should be a programming language for everyone.
Python has the same aura and I hope that Small Basic, Visual Basic and
Small Visual Basic will continue the history of Basic.

Do you know that I still have some old Basic Dialects on 3.5" floppy disks?
GW-Basic, QBasic, QuickBasic and the single version of Visual Basic for
DOS. I have two old and running computers from the 1990s with the operating
system DOS. I am a fan of old computer books from the 1980s and 1990s. They
could be a nice part of a computer museum: a bookshelf with a lot of old
computer and programming books. My channel Basic-Retro-Programming on
Tumblr has also this background.

Kind regards ... Gregor

Mohammad Hamdy Ghanem ***@***.***> schrieb am Mo., 22. Mai
2023, 23:09:
