### ISSUE TITLE
Gradient forecolor of text in a textbox may cause an exception while inputting with some kinds of input methods.

### ISSUE THREAD

**Issue by dynamicboy** [VBAndCs/sVB-Small-Visual-Basic#40]
Version: 2.8.7.5
Details:
Step 1: Drag a textbox from the toolbox to the form
Step 2: Set the Forecolor to a gradient color
Step 3: Run the application
Step 4: Input some text. It's ok with any straightforward English input method and some Chinese input methods which compose words in the candidates box first, then send it to the textbox. However, with input methods that send English letters to the textbox first and then replace them with composed words in the candidates box ( I use Microsoft Wubi Input Method), an exception will occur.

In 2.8.7.5, the form will freeze and exit.

In 2.8.7.3, it may throw an exception like the one below:
 "Can't convert System.Windows.Media.LinearGradientBrush object to type System.Windows.Media.SolidColorBrush".

**Comment by VBAndCs** [comment]
Hi @dynamicboy,
I can't understand this, because I've never used such input methods and I have no knowledge about Chinese languages. If some Chinese VB.NET programmer can look at this in the source code and propose a fix, I will use it, otherwise, I can't do anything right now.
Thanks.

________________________________
From: dynamicboy ***@***.***>
Sent: Saturday, December 30, 2023 8:06 AM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Gradient forecolor of text in a textbox may cause an exception while inputting with some kinds of input methods. (Issue #40)


Version: 2.8.7.5
Details:
Step 1: Drag a textbox from the toolbox to the form
Step 2: Set the Forecolor to a gradient color
Step 3: Run the application
Step 4: Input some text. It's ok with any straightforward English input method and some Chinese input methods which compose words in the candidates box first, then send it to the textbox. However, with input methods that send English letters to the textbox first and then replace them with composed words in the candidates box ( I use Microsoft Wubi Input Method), an exception will occur.

In 2.8.7.5, the form will freeze and exit.

In 2.8.7.3, it may throw an exception like the one below:
"Can't convert System.Windows.Media.LinearGradientBrush object to type System.Windows.Media.SolidColorBrush".

**Comment by VBAndCs** [comment]
Is this issue solved in current version?
If not, please reopen it until someone can help solving it.
Thanks.
________________________________
