### ISSUE TITLE
Dragging a flow chart or geometric shapes onto the form will prevent the form from launching?

### ISSUE THREAD

**Issue by dynamicboy** [VBAndCs/sVB-Small-Visual-Basic#42]
Version:2.8.7.5
Details:
If I drag a flow chart or geometric shape onto the form, then I can't launch the form; it's behind the purple surface.
Screenshot:
![2024-01-01_040502](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/7421525/75922d10-4c8f-4098-9161-f0117ddc93cc)

**Comment by VBAndCs** [comment]
The funny thing is that the flowchart and geometric tabs existed before the controls tab, and they were working since the very first trails of the form designer :D

In recent updates, I made some changes to shorten the xaml file by removing default font properties, but this caused errors with flowchart and geometric shapes.

I've fixed the issue, and everything works fine in the upcoming version.

Thanks


________________________________
From: dynamicboy ***@***.***>
Sent: Sunday, December 31, 2023 8:07 PM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Dragging a flow chart or geometric shapes onto the form will prevent the form from launching? (Issue #42)


Version:2.8.7.5
Details:
If I drag a flow chart or geometric shape onto the form, then I can't launch the form; it's behind the purple surface.
Screenshot:
2024-01-01_040502.png (view on web)<https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/7421525/75922d10-4c8f-4098-9161-f0117ddc93cc>
