### ISSUE TITLE
The position of the image after drawing a colorful shape with the turtle ...

### ISSUE THREAD

**Issue by boa2145** [VBAndCs/sVB-Small-Visual-Basic#54]
Hello Mohammad,

For example, if I have drawn a flag with the turtle and filled it with color and then want to put the flag's logo on it, the logo is located  behind the turtle's drawing but is not visible on the drawing. What could be the reason? On the other hand, if I draw the same flag with colored rectangles, I don't have the problem when I then put the logo on the drawing. I would like to use the turtle to slightly animate the drawing of the flag.

Regards ... Gregor

**Comment by VBAndCs** [comment]
Hi Gregor:
The image is drawn on the form background, which makes any other shape or control appear over it.
You should add a label on the GW and set it's Image property to the image path. You can also use the label's BringToFront method to ensure it's on top of the turtle shape.
I hope you start using sVB tools instead of sticking with the old SB ways.
Thanks.

________________________________
From: Gregor ***@***.***>
Sent: Tuesday, January 30, 2024 11:09 AM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] The position of the image after drawing a colorful shape with the turtle ... (Issue #54)


Hello Mohammad,

For example, if I have drawn a flag with the turtle and filled it with color and then want to put the flag's logo on it, the logo is located behind the turtle's drawing but is not visible on the drawing. What could be the reason? On the other hand, if I draw the same flag with colored rectangles, I don't have the problem when I then put the logo on the drawing. I would like to use the turtle to slightly animate the drawing of the flag.

Regards ... Gregor

**Comment by VBAndCs** [comment]
And please update to the latest sVB version to have the BringToFront merhod

________________________________
From: Gregor ***@***.***>
Sent: Tuesday, January 30, 2024 11:09 AM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] The position of the image after drawing a colorful shape with the turtle ... (Issue #54)


Hello Mohammad,

For example, if I have drawn a flag with the turtle and filled it with color and then want to put the flag's logo on it, the logo is located behind the turtle's drawing but is not visible on the drawing. What could be the reason? On the other hand, if I draw the same flag with colored rectangles, I don't have the problem when I then put the logo on the drawing. I would like to use the turtle to slightly animate the drawing of the flag.

Regards ... Gregor

**Comment by boa2145** [comment]
Hello Mohammad,

Thanks for your replies. I currently use sVB v2.8.7 and have to update it. I thought about turtle graphics. I really like this kind of logo programming very much. It is one of my favourite kinds to program with Small Basic and Python. Is it right that I can only use the turtle with the GraphicsWindow object? So, If I want to program a flag with your form designer, I can't use the turtle, but I am able to use all elements of the form designer's toolbox, right?

**Comment by VBAndCs** [comment]
I allowed to use all sVB controls on the GW. After all the GQ is a Form, and you can use
f = GW.AsForm()
So you can `f` as any other form.
You can also create a form with textboxes and buttons to control the turtle behaviour, like providing the polygon sides and Side length, then click the button to make the turtle draw the requested polygon.
```
Sub Button1_OnClick()
   GraphicsWindow.Clear()
   DrawPolygon(TxtSides.Text, TxtLen.Text)
EndSub

Sub DrawPolygon(n, l)
   a = 360 / n
   For i = 1 To n
      Turtle.Move(l)
      Turtle.Turn(a)
   Next
EndSub
```

So, it is OK to use the GW and Turtle, but you should read about all other sVB stuff because you can use it with them as well to create amazing apps.
Thanks.

________________________________

**Comment by VBAndCs** [comment]
I have no access to my GitHub account right now. I just reply using email, and publish updates to the source code using command line. The read me contains a link to the sVB installer on the VS Marketplace, which I update frequently:

https://marketplace.visualstudio.com/items?itemName=ModernVBNET.sVBInstaller

________________________________

**Comment by boa2145** [comment]
Hi Mohammad,

I tried to install sVB 2.8.9.3 from the marketplace on my pc. It was possible to download the file, but it happened nothing after double clicking on the file. I do not know why it happened nothing. I deactivated Norton Utilities (Auto Protect and Smart Firewall), but I am not able to install your sVB file.

**Comment by VBAndCs** [comment]
Make sure that the file name is sVB_2.8.9.3_Installer.msi and its size is 20.7MB or redownload it.
Note the browser may ask you to trust the file and to keep it, otherwise it may not complete downloading it.
I downloaded the file and it works fine on my PC.
Also, make sure that you give the file permission to run. Right click it, and at the end of the properties window choose to unblock the file.
You may also move the file to another folder away of windows drive.
Good luck.


________________________________

**Comment by boa2145** [comment]
Hello Mohammad,

I was able to install sVB 2.8.9.3 on my pc. I changed the browser (Brave -> Edge) and deactivated Auto Protect and Smart Firewall by Norton 360. 

![Norton Message](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/113761330/00eff60f-0b65-4039-8cee-063e67508ba3)

I tried to install for everyone and got this message.

![Installing Message](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/113761330/6dcba8c3-93ae-45b9-b696-d0537758b6ff)

After that I installed only for me and it worked.

**Comment by VBAndCs** [comment]
I just published the first book of the "Small Visual Basic Kid Programmer" series on Amazon: https://www.amazon.com/dp/B0CVK1BMC9

________________________________
From: Gregor ***@***.***>
Sent: Tuesday, January 30, 2024 11:09 AM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] The position of the image after drawing a colorful shape with the turtle ... (Issue #54)


Hello Mohammad,

For example, if I have drawn a flag with the turtle and filled it with color and then want to put the flag's logo on it, the logo is located behind the turtle's drawing but is not visible on the drawing. What could be the reason? On the other hand, if I draw the same flag with colored rectangles, I don't have the problem when I then put the logo on the drawing. I would like to use the turtle to slightly animate the drawing of the flag.

Regards ... Gregor

**Comment by boa2145** [comment]
Hello Mohammad, This is good news Mohammad that you have published a book about programming with Small Visual Basic on Amazon. Congratulations! I will buy it for my Kindle and look forward to reading your new book. By the way, I keep looking at your sVB manual and reading sections that interest me. Regards ... Gregor

**Comment by VBAndCs** [comment]
Thanks Gregor.
I hope you find it useful.
Regards.

________________________________
