### ISSUE TITLE
May 1, 2024, Safe the date ...

### ISSUE THREAD

**Issue by boa2145** [VBAndCs/sVB-Small-Visual-Basic#56]
Hi Mohammad, I'm waiting for May 1, 2024, the 60th anniversary since the publication of BASIC by John Kemeny and Thomas Kurtz. Maybe you or other BASIC enthusiasts will publish some interesting topic on the internet.

Regards ... Gregor

![image](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/113761330/5783676f-680c-43e2-a8b2-b6d4f5475edb)

**Comment by VBAndCs** [comment]
Hi @Gregor,
I hope so. I am trying to alert VBers for this occasion, so that they can be prepared. I hope I can release sVB 3.0 by this date, and hope that Anthony Green can release ModVB, and the same for other VB new dialects like TwinBasic. It is also a good idea to have hundreds or thousands of articles and memories about BASIC.
I also hope that Dartmouth university (the BASIC homeland), do a big event about that.
So, let's spread the word and be ready.
________________________________
From: Gregor ***@***.***>
Sent: Thursday, February 22, 2024 8:22 PM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] May 1, 2024, Safe the date ... (Issue #56)


Hi Mohammad, I'm waiting for May 1, 2024, the 60th anniversary since the publication of BASIC by John Kemeny and Thomas Kurtz. Maybe you or other BASIC enthusiasts will publish some interesting topic on the internet.

Regards ... Gregor

image.png (view on web)<https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/113761330/5783676f-680c-43e2-a8b2-b6d4f5475edb>

https://time.com/69316/basic/<url>

**Comment by boa2145** [comment]
Good morning Mohammad, 

Yes, I also hope that there will be many contributions to Basic's 60th birthday, especially from Dartmouth University. Back then, BASIC gave me access to programming, which wasn't possible with C and Turbo Pascal. There were and are so many great Basic dialects, especially from Microsoft. A lot has changed since then and new programming languages have been added (e.g. Visual Basic, Scratch and Python). I am particularly interested in its use in the education sector, i.e. how programming languages can be taught to children and young people, but also to adults who are young at heart. BASIC used to lay the foundation for this and I really appreciate the work of Kemeny and Kurtz. I am also very happy that you have expanded Small Basic and that children and young people can benefit from it.

Regards from Kiel near Baltic Sea ... Gregor
