### ISSUE TITLE
Don't be able to contact you on Facebook ...

### ISSUE THREAD

**Issue by boa2145** [VBAndCs/sVB-Small-Visual-Basic#65]
Hello Mohammad,

I am also a member of your sVB community and wanted to public a post about Turtle Programming some days ago: 21 Shapes For Kids, Teenagers And Adults. It was a lot of work for me and you still have to enable my post. Ist it possible to release my post on your sVB site on Facebook?

Regards ... Gregor

**Comment by VBAndCs** [comment]
Sorry. I didn't get any notifications about that. I reviewed the notification options, and it is on!
In such cases, you can send me a massage on this Feacebook page:
https://www.facebook.com/SmallVisualBasic/

________________________________
From: Gregor ***@***.***>
Sent: Sunday, May 26, 2024 7:29 AM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Don't be able to contact you on Facebook ... (Issue #65)


Hello Mohammad,

I am also a member of your sVB community and wanted to public a post about Turtle Programming some days ago: 21 Shapes For Kids, Teenagers And Adults. It was a lot of work for me and you still have to enable my post. Ist it possible to release my post on your sVB site on Facebook?

Regards ... Gregor

**Comment by boa2145** [comment]
Hello Mohammad, Thanks for your reply. I sent you a message in your group on Facebook: May-16-2024, but now my post is online in your group. I do not have so much fun with Small Basic Enthusiast's Group. It is not very interesting for me to show my tries with Small (Visual) Basic. Regards ... Gregor

**Comment by VBAndCs** [comment]
Hi Gregor,
Please close your issues that are fixed, because I don't have full access to this repo right now.
Thanks.


________________________________
From: Gregor ***@***.***>
Sent: Sunday, May 26, 2024 7:29 AM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Don't be able to contact you on Facebook ... (Issue #65)


Hello Mohammad,

I am also a member of your sVB community and wanted to public a post about Turtle Programming some days ago: 21 Shapes For Kids, Teenagers And Adults. It was a lot of work for me and you still have to enable my post. Ist it possible to release my post on your sVB site on Facebook?

Regards ... Gregor

**Comment by boa2145** [comment]
Hi Mohammad, I will close my issues that are fixed next time. Best wishes
... Gregor

Mohammad Hamdy Ghanem ***@***.***> schrieb am Sa., 15. Juni
2024, 13:15:

**Comment by VBAndCs** [comment]
Thanks, but I need to close old issues too, including this one.
Thanks.
________________________________

**Comment by boa2145** [comment]
Hello Mohammad,

I closed my 8 old issues on GitHub a few minutes ago. There are still 2
open issues from you (#8: Small Visual Basic is out there but need to be
heard of!) and Dynamicboy (#40: Gradient forecolor of text in a textbox may
cause an exception white inpuuting with some kinds of input methods). If
you want, you can use my private email-address in future. Then we are
independent of GitHub.

Best regards ... Gregor
***@***.***

Am Sa., 15. Juni 2024 um 19:16 Uhr schrieb Mohammad Hamdy Ghanem <
***@***.***>:

**Comment by VBAndCs** [comment]
Thanks.
Publishing issues here allows users to find fixes, and allows contributors to find open issues to fix.
