### ISSUE TITLE
Closing issues that are closed

### ISSUE THREAD

**Issue by stuwilmur** [VBAndCs/sVB-Small-Visual-Basic#66]
Hi @VBAndCs,

I noticed that most of the currently open issues are in fact addressed/fixed: it may be helpful to mark these as done; this may be helpful for potential contributors who are looking to work on an issue that has no fix to find one more easily.

This is a really impressive project, particularly given the number of contributors.

**Comment by VBAndCs** [comment]
Hi stu:
Thanks for your concern and advice.
You may notice that there are some closed issues before a certain date. That was before GitHub forced the 2 factor authentication, which I can't use vis SMS because Egypt is not in its list!
I will not install extensions nor extra apps. If fact I am wondering why they can't just verify login via email as it was?
Until this situation changes, I only can do two things:
1. Reply on issues via email
2. Upload updates via git consol.
And if this situation is not fixed or faceed any new problems, I will move the source code to another server.
So, the only way to close an issue is by its creator. You should do that for this one :D
Thanks.

________________________________
From: Stu Murray ***@***.***>
Sent: Thursday, June 13, 2024 2:23 PM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Mohammad Hamdy Ghanem ***@***.***>; Mention ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Closing issues that are closed (Issue #66)


Hi @VBAndCs<https://github.com/VBAndCs>,

I noticed that most of the currently open issues are in fact addressed/fixed: it may be helpful to mark these as done; this may be helpful for potential contributors who are looking to work on an issue that has no fix to find one more easily.

This is a really impressive project, particularly given the number of contributors.

**Comment by stuwilmur** [comment]
Hi @VBAndCs,

Understood: that must be very frustrating: I hope Github enable SMS authentication for you soon; have you perhaps explored using an authenticator app such as Duo or MS authenticator?

I will close this issue 🙂

**Comment by stuwilmur** [comment]
Closed
