### ISSUE TITLE
Forms added via the Forms.AddForm() method do not support size assignment. 

### ISSUE THREAD

**Issue by dynamicboy** [VBAndCs/sVB-Small-Visual-Basic#75]
version: sVB 3.0.8.1
details: Forms added via the Forms.AddForm() method do not support size assignment. 
code:
``` Small Visual Basic
AnotherForm = Forms.AddForm("AnotherForm")
AnotherForm.Width = Me.Width
AnotherForm.Height = Me.Width / 1.88

' LblCanvas = AnotherForm.AddLabel("lblCanvas", 0, 0, AnotherForm.Width, AnotherForm.Height)
LblCanvas = AnotherForm.AddLabel("lblCanvas", 0, 0, 300, 100)


LblCanvas.BackColor = Colors.Tomato

AnotherForm.BackColor = Colors.YellowGreen
AnotherForm.Hide()



' Drag a button onto the form. ------------------------------------------------
Sub Button1_OnClick()
   AnotherForm.Show()
EndSub
```

If uncomment line 5 and comment line 6, the lblCanvas can't be seen as it's size is zero which is the value of AnotherForm's size.

screenshot:
![2024-08-06_212707](https://github.com/user-attachments/assets/0a6a764c-40ee-4973-9025-3ea4c4d6a514)
![2024-08-06_212735](https://github.com/user-attachments/assets/adc2968f-13f2-4aa6-8cfa-57f2da7b099a)

**Comment by VBAndCs** [comment]
Adding a form doesn't show it. So, the line:
AnotherForm.Hide()
actually is not necessary, since the form is not shown yet.
sVB is created using WPF. In WPF, there Width and ActualWidth properties and they can have different values! In sVB I read the ActualWidth of the control to give you the exact measure, so, before the form is displayed for the first time, its actual width is 0.
To solve this, you just need to show the form:
 AnotherForm.Show()
Then hide it again as you did.
Please close this issue if you accept this answer.
Thanks.

________________________________
From: dynamicboy ***@***.***>
Sent: Tuesday, August 6, 2024 2:07 PM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Forms added via the Forms.AddForm() method do not support size assignment. (Issue #75)


version: sVB 3.0.8.1
details: Forms added via the Forms.AddForm() method do not support size assignment.
code:

AnotherForm = Forms.AddForm("AnotherForm")
AnotherForm.Width = Me.Width
AnotherForm.Height = Me.Width / 1.88

' LblCanvas = AnotherForm.AddLabel("lblCanvas", 0, 0, AnotherForm.Width, AnotherForm.Height)
LblCanvas = AnotherForm.AddLabel("lblCanvas", 0, 0, 300, 100)


LblCanvas.BackColor = Colors.Tomato

AnotherForm.BackColor = Colors.YellowGreen
AnotherForm.Hide()



' Drag a button onto the form. ------------------------------------------------
Sub Button1_OnClick()
   AnotherForm.Show()
EndSub


If uncomment line 5 and comment line 6, the lblCanvas can't be seen as it's size is zero which is the value of AnotherForm's size.

screenshot:
2024-08-06_212707.png (view on web)<https://github.com/user-attachments/assets/0a6a764c-40ee-4973-9025-3ea4c4d6a514>
2024-08-06_212735.png (view on web)<https://github.com/user-attachments/assets/adc2968f-13f2-4aa6-8cfa-57f2da7b099a>

**Comment by VBAndCs** [comment]
Or a better solution is to adjust the label size after showing the form, to avoid showing and hiding it:

Sub Button1_OnClick()
   AnotherForm.Show()
   LblCanvas.Width = AnotherForm.Width
   LblCanvas.Height = AnotherForm.Height
EndSub
________________________________
From: dynamicboy ***@***.***>
Sent: Tuesday, August 6, 2024 2:07 PM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Forms added via the Forms.AddForm() method do not support size assignment. (Issue #75)


version: sVB 3.0.8.1
details: Forms added via the Forms.AddForm() method do not support size assignment.
code:

AnotherForm = Forms.AddForm("AnotherForm")
AnotherForm.Width = Me.Width
AnotherForm.Height = Me.Width / 1.88

' LblCanvas = AnotherForm.AddLabel("lblCanvas", 0, 0, AnotherForm.Width, AnotherForm.Height)
LblCanvas = AnotherForm.AddLabel("lblCanvas", 0, 0, 300, 100)


LblCanvas.BackColor = Colors.Tomato

AnotherForm.BackColor = Colors.YellowGreen
AnotherForm.Hide()



' Drag a button onto the form. ------------------------------------------------
Sub Button1_OnClick()
   AnotherForm.Show()
EndSub


If uncomment line 5 and comment line 6, the lblCanvas can't be seen as it's size is zero which is the value of AnotherForm's size.

screenshot:
2024-08-06_212707.png (view on web)<https://github.com/user-attachments/assets/0a6a764c-40ee-4973-9025-3ea4c4d6a514>
2024-08-06_212735.png (view on web)<https://github.com/user-attachments/assets/adc2968f-13f2-4aa6-8cfa-57f2da7b099a>

**Comment by VBAndCs** [comment]
A third solution is to use the OnShown event to add the label and set its properties.
Not that either way, your program has an iassue. If you closed the AnotherForm then clicked the button, the AnotherForm.Show method will cause an error because the form is disposed and no longer exists.
To fix this, you can use the OnClosing ecent to cancel the closing action and hide the form instead, but you will need also to uase the closed event of the main form to terminate the program, otherwise the AnotherForm will be alive forever and the program will not terminate. This is the code:
AnotherForm = Forms.AddForm("AnotherForm")
AnotherForm.Width = Me.Width
AnotherForm.Height = Me.Width / 1.88
AnotherForm.BackColor = Colors.YellowGreen
AnotherForm.OnShown = AnotherForm_OnShown
AnotherForm.OnClosing = AnotherForm_OnClosing

' ------------------------------------------------
Sub AnotherForm_OnShown()
   lblCanvas = AnotherForm.AddLabel("lblCanvas", 0, 0, AnotherForm.Width, AnotherForm.Height)
   lblCanvas.BackColor = Colors.Tomato
EndSub

' ------------------------------------------------
Sub Button1_OnClick()
   AnotherForm.Show()
EndSub

' ------------------------------------------------
Sub AnotherForm_OnClosing()
   Event.Handled = True
   AnotherForm.Hide()
EndSub


' ------------------------------------------------
Sub Form1_OnClosed()
   Program.End()
EndSub
________________________________

**Comment by dynamicboy** [comment]
Good Point! Got it! Thanks!
