### ISSUE TITLE
Can't set label2.image with label1.image

### ISSUE THREAD

**Issue by dynamicboy** [VBAndCs/sVB-Small-Visual-Basic#76]
sVB: 3.0.8.2
details: Can't set label2.image with label1.image while label2.image includes non-ASCII characters.
screenshot:
![2024-08-09_025616](https://github.com/user-attachments/assets/727d2f54-2b6b-4f6d-ab2b-5cd12ab0657c)
![2024-08-09_025601](https://github.com/user-attachments/assets/e3d433b9-5a4c-41e2-88a0-ff063b4aea23)

**Comment by VBAndCs** [comment]
The image path can be any absolute or relative uri, that can also contain environment variables and non enplish chars, so it is being processed to get the exact path. The problem is that when you read this path back, it is read from the shown image, which will not be input path.
You can avoid this by saving the path in a variable and reuse it. Though I fixed this issue for convenance by saving the original path in an attached property for each label, so in the next version you will get back the exact string you put in the image property.
Thanks.
________________________________
From: dynamicboy ***@***.***>
Sent: Saturday, August 10, 2024 8:53 AM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Can't set label2.image with label1.image (Issue #76)


sVB: 3.0.8.2
screenshot:
2024-08-09_025616.png (view on web)<https://github.com/user-attachments/assets/727d2f54-2b6b-4f6d-ab2b-5cd12ab0657c>
2024-08-09_025601.png (view on web)<https://github.com/user-attachments/assets/e3d433b9-5a4c-41e2-88a0-ff063b4aea23>
