### ISSUE TITLE
How do I delete the image file that has been set as Label1.Image?

### ISSUE THREAD

**Issue by dynamicboy** [VBAndCs/sVB-Small-Visual-Basic#77]
version: sVB: 3.0.8.2
details: How do I delete the image file that has been set as Label1.Image?
I have two folders containing different sets of images, which I display using labels. I want to move these images between the two folders by dragging the labels. The process involves two steps: first, copying the target image to the other folder, and then deleting the original image. However, I'm encountering an issue in the second step, as I'm unable to delete the original image. The error message indicates that the image is being used by another process. How can I release the image and delete it?

sample code:

``` Small Visual Basic
Label1.Image = "E:\1.png"



' ------------------------------------------------
Sub Button1_OnClick()
   imgSrc = GBImage.UrlDecode(Label1.Image)
   
' the following three ways don't work.
   Label1.Image = ""
   Label1.Text = ""
   Me.RemoveControl(Label1)
   
   success = File.DeleteFile(imgSrc)   
   If success = True Then
      Dialogs.MsgBox("Result", "Delete successfully")
   Else
      Dialogs.MsgBox("Result", "Delete failure")
      Label2.Text = File.LastError
   EndIf
   
EndSub


```

**Comment by VBAndCs** [comment]
Try removing the displayed image before deleting or moving the image file by:
Label1.Image = ""

Please close the solved issues.
Thanks.
________________________________
From: dynamicboy ***@***.***>
Sent: Saturday, August 10, 2024 4:09 PM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] How do I delete the image file that has been set as Label1.Image? (Issue #77)


version: sVB: 3.0.8.2
details: How do I delete the image file that has been set as Label1.Image?
I have two folders containing different sets of images, which I display using labels. I want to move these images between the two folders by dragging the labels. The process involves two steps: first, copying the target image to the other folder, and then deleting the original image. However, I'm encountering an issue in the second step, as I'm unable to delete the original image. The error message indicates that the image is being used by another process. How can I release the image and delete it?

sample code:

Label1.Image = "E:\1.png"



' ------------------------------------------------
Sub Button1_OnClick()
   imgSrc = GBImage.UrlDecode(Label1.Image)

' the following three ways don't work.
   Label1.Image = ""
   Label1.Text = ""
   Me.RemoveControl(Label1)

   success = File.DeleteFile(imgSrc)
   If success = True Then
      Dialogs.MsgBox("Result", "Delete successfully")
   Else
      Dialogs.MsgBox("Result", "Delete failure")
      Label2.Text = File.LastError
   EndIf

EndSub

**Comment by VBAndCs** [comment]
I see you already reomved the displayed image!
I will look into it.

________________________________
From: dynamicboy ***@***.***>
Sent: Saturday, August 10, 2024 4:09 PM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] How do I delete the image file that has been set as Label1.Image? (Issue #77)


version: sVB: 3.0.8.2
details: How do I delete the image file that has been set as Label1.Image?
I have two folders containing different sets of images, which I display using labels. I want to move these images between the two folders by dragging the labels. The process involves two steps: first, copying the target image to the other folder, and then deleting the original image. However, I'm encountering an issue in the second step, as I'm unable to delete the original image. The error message indicates that the image is being used by another process. How can I release the image and delete it?

sample code:

Label1.Image = "E:\1.png"



' ------------------------------------------------
Sub Button1_OnClick()
   imgSrc = GBImage.UrlDecode(Label1.Image)

' the following three ways don't work.
   Label1.Image = ""
   Label1.Text = ""
   Me.RemoveControl(Label1)

   success = File.DeleteFile(imgSrc)
   If success = True Then
      Dialogs.MsgBox("Result", "Delete successfully")
   Else
      Dialogs.MsgBox("Result", "Delete failure")
      Label2.Text = File.LastError
   EndIf

EndSub

**Comment by VBAndCs** [comment]
This one was hard!
The WPF image locks the image file until the process is terminated!
To solve this, the image should be cached on loading. This code may help WPF users to solve such issue:
```
Dim img As New BitmapImage()
img.BeginInit()
img.CacheOption = BitmapCacheOption.OnLoad
img.UriSource = New Uri(imgFile)
img.EndInit()
lbl.Content = New Wpf.Image() With {.Source = img}
```

So, this issue will be fixed in the next release, which will conyain some other minor fixes and some new samples. It may also include an updated version of LitDev, and an interesting sample called "Falling balls" that uses its PhysicsEngine.
I also added a Math.Rnd(min, max) method to get a random number in the given range to ease the pain of doing that with the GetRandomNumber(max) and also use a shorter name!
So, in sVB 3.0.8.3 you will not need to remove the image from the label before deleting the file, because the image is cached and will kept displayed.
Thanks.
________________________________
From: dynamicboy ***@***.***>
Sent: Saturday, August 10, 2024 4:09 PM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] How do I delete the image file that has been set as Label1.Image? (Issue #77)


version: sVB: 3.0.8.2
details: How do I delete the image file that has been set as Label1.Image?
I have two folders containing different sets of images, which I display using labels. I want to move these images between the two folders by dragging the labels. The process involves two steps: first, copying the target image to the other folder, and then deleting the original image. However, I'm encountering an issue in the second step, as I'm unable to delete the original image. The error message indicates that the image is being used by another process. How can I release the image and delete it?

sample code:

Label1.Image = "E:\1.png"



' ------------------------------------------------
Sub Button1_OnClick()
   imgSrc = GBImage.UrlDecode(Label1.Image)

' the following three ways don't work.
   Label1.Image = ""
   Label1.Text = ""
   Me.RemoveControl(Label1)

   success = File.DeleteFile(imgSrc)
   If success = True Then
      Dialogs.MsgBox("Result", "Delete successfully")
   Else
      Dialogs.MsgBox("Result", "Delete failure")
      Label2.Text = File.LastError
   EndIf

EndSub
