### ISSUE TITLE
GraphicsWindow.FillPolygon() ...

### ISSUE THREAD

**Issue by boa2145** [VBAndCs/sVB-Small-Visual-Basic#78]
Hello Mohammad,

I need your help, because I do not know how to handle the method "FillPolygon()" of the graphicswindow object. I didn't find any reference to this method in your manual.

GraphicsWindow.FillPolygon(xOffset, yOffset, xScale, yScale, pointsArr)

Fills the polygon that is represented by the given points array with the brush of the graphics window.

Parameters Info: 

xOffset: The horizontal offest to add to the x-cordinate of each point of the polygon.
yOffset: The vertical offest to add to the y-cordinate of each point of the polygon.
xScale: The factor to multiply the polygon width by.
yScale: The factor to multiply the polygon height by.
pointsArr: An array of points representing the heads of the polygn. Each item in this array is an array containing the x and y of the point.

Do you have any samples for this method?

Regards ... Gregor

**Comment by VBAndCs** [comment]
Hi Gregor:
This method is explained in the sVB docs PDF. You can search for its name by pressing Ctrl+F in your PDF viewer. In the latest version of the book, it is in page 610, and this is the sample given in the book:
You can see this method in action in the "Draw Pentagon" project in the samples folder.
The following code fills a star with a gradient color and outlines it:
StarPoints = {
   {40.00, 0.50},
   {49.34, 28.76},
   {79.50, 28.76},
   {55.10, 46.24},
   {64.35, 74.50},
   {40.00, 57.02},
   {15.60, 74.50},
   {24.90, 46.24},
   {0.50, 28.76},
   {30.66, 28.76}
}

GraphicsWindow.BrushColor = Colors.Gold
GraphicsWindow.GradientEndColor = Colors.White
GW.FillPolygon(80, 50, 3, 3, StarPoints)
GraphicsWindow.PenColor = Colors.SaddleBrown
GraphicsWindow.PenWidth = 1.1
GW.DrawPolygon(80, 50, 3, 3, StarPoints)
________________________________
From: Gregor ***@***.***>
Sent: Saturday, August 10, 2024 7:43 PM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] GraphicsWindow.FillPolygon() ... (Issue #78)


Hello Mohammad,

I need your help, because I do not know how to handle the method "FillPolygon()" of the graphicswindow object. I didn't find any reference to this method in your manual.

GraphicsWindow.FillPolygon(xOffset, yOffset, xScale, yScale, pointsArr)

Fills the polygon that is represented by the given points array with the brush of the graphics window.

Parameters Info:

xOffset: The horizontal offest to add to the x-cordinate of each point of the polygon.
yOffset: The vertical offest to add to the y-cordinate of each point of the polygon.
xScale: The factor to multiply the polygon width by.
yScale: The factor to multiply the polygon height by.
pointsArr: An array of points representing the heads of the polygn. Each item in this array is an array containing the x and y of the point.

Do you have any samples for this method?

Regards ... Gregor

**Comment by boa2145** [comment]
Good evening Mohammad, Thanks for your replay. I will try it out to draw a polygon with the method "DrawPolygon()". I probably have to code some polygons and then I will be in the picture how the methods works. Regards ... Gregor

**Comment by boa2145** [comment]
Hello Mohammad, now I was able to use the "FillPolygon()" and "DrawPolygon()" methods and understood "Offset" and "Scale". However, when it comes to the array with the coordinates for the position of the geometric figure, it is not yet clear to me whether there is a direction of rotation. I assume it is from left to right. Is there an order to be observed?

The sample file "DrawPentagon" shows this code:

GraphicsWindow.PenColor = Colors.Black
GraphicsWindow.PenWidth = 3
GraphicsWindow.BrushColor = Colors.Red
Star = Shapes.AddPolygon(
   {
      {0, 100},
      {76.5, 100},
      {100, 25},
      {123.5, 100},
      {200, 100},
      {140, 142.5},
      {160, 200},
      {100, 145},
      {40, 200},
      {62, 142.5}
   }
)

Shapes.Move(Star, 200, 20)

The sample file "DrawPentagon2" shows this code:

Label1.AddPolygon(
   {
      {0, 100},
      {76.5, 100},
      {100, 25},
      {123.5, 100},
      {200, 100},
      {140, 142.5},
      {160, 200},
      {100, 145},
      {40, 200},
      {62, 142.5}
   },
   Colors.Black, 3, Colors.Red
)

Geometrics.AllowDrag(Label1)

There are no methods like "FillPolygon()" or "DrawPolygon()" and, sorry,  I could not find an example in your handbook.

Regards ... Gregor

**Comment by VBAndCs** [comment]
The points are the vertexes of the pentagon. You can arrange them as you like, to draw a line between each successive points. Crossed line are allowed, which make it possible to draw a star. The "Draw Pentagon"  (not  "Draw Pentagon2") shows five shapes.
This method is explained in page 610 on the latest version of the pdf, which is also published online :
https://drive.google.com/file/d/1pCnB4_7pEBc_wT2u258MmutYCuXwpvjN/edit?page=610
________________________________

**Comment by VBAndCs** [comment]
Try this:

Points = {
   {0, 0},
   {200, 0},
   {200, 200},
   {0, 200},
   {0, 0},
   {200, 200},
   {200, 0},
   {0, 200},
   {0, 0}
}
GW.PenColor = Colors.Black
GW.BrushColor = Colors.Red
GW.DrawPolygon(100, 100, 1, 1, Points)
GW.FillPolygon(100, 100, 1, 1, Points)
________________________________

**Comment by boa2145** [comment]
Hello Mohammad, Thanks for your help! I am able to see page 610 now. Well, I tried the method out to code the flag of "Trinidad And Tobago". I coded this flag only with "FillPolygon"  and also with the turtle and another one as a mix of graphics and turtle methods. I published my file with the method "FillPolygon" and you can see my results. The code of my published file is "QXFK14.000". The first letter is a Q and not an O. Best wishes ... Gregor

![The Flags Of The World - Trinidad And Tobago](https://github.com/user-attachments/assets/5e7b5a38-943b-426f-bb24-0ff3567a786b)

**Comment by boa2145** [comment]
https://www.tumblr.com/blog/small-basic-programming
