### ISSUE TITLE
Accidentally published private or unfinished project to web due to lack of confirmation step

### ISSUE THREAD

**Issue by dynamicboy** [VBAndCs/sVB-Small-Visual-Basic#84]
I've accidentally hit 'Ctrl + Shift + S' or the 'Publish' button on the toolbar multiple times, resulting in my unfinished or private projects being published to the web.

It's really frustrating! There's no confirmation step in the publishing process.

So, I hope the next version of sVB will cancel the keyboard shortcut for publishing and intercept the publishing process with a confirmation dialog.

Additionally, I suggest moving the publish button to the end of the toolbar.

![2024-09-18_203044](https://github.com/user-attachments/assets/cf441190-4532-4be8-ab31-c42a3ec8b063)

**Comment by dynamicboy** [comment]
I may temporarily disconnect from the internet while coding with sVB to avoid accidentally publishing the project online.

**Comment by VBAndCs** [comment]
This can be easily done (except for changing the buttons location)
I had added some restrictions before, like preventing publishing too small source codes, and checking the source for compiler errors before publishing it. I will also add a confirmation message before publishing.
Thanks.
________________________________

**Comment by VBAndCs** [comment]
Fixed in sVB 3.0.9.6
https://marketplace.visualstudio.com/items?itemName=ModernVBNET.sVBInstaller

________________________________
From: dynamicboy ***@***.***>
Sent: Wednesday, September 18, 2024 12:50 PM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Accidentally published private or unfinished project to web due to lack of confirmation step (Issue #84)


I've accidentally hit 'Ctrl + Shift + S' or the 'Publish' button on the toolbar multiple times, resulting in my unfinished or private projects being published to the web.

It's really frustrating! There's no confirmation step in the publishing process.

So, I hope the next version of sVB will cancel the keyboard shortcut for publishing and intercept the publishing process with a confirmation dialog.

Additionally, I suggest moving the publish button to the end of the toolbar.

2024-09-18_203044.png (view on web)<https://github.com/user-attachments/assets/cf441190-4532-4be8-ab31-c42a3ec8b063>
