### ISSUE TITLE
sort question

### ISSUE THREAD

**Issue by Drugo67** [VBAndCs/sVB-Small-Visual-Basic#94]
Hi Mohammad! Congratulations for the level 2 book. I think it is very useful! I wanted to ask 2 questions. One thing that I found useful in VB6 was to use the "Sort" member especially for Listboxes and ComboBoxes, and I wondered why it was not developed in sVB. And the second question is about the possibility of formatting a text in the center of a label. I see that there are many possibilities to change fonts, colors, etc... but there is no possibility to center it or format it on the left. How could I do it? thanks in advance and congratulations again

**Comment by VBAndCs** [comment]
Hi Drugo67,
Thanks for your kind words.
Small visual Basic is not meant for production. It is just an educational language, and every new property and method added increases the complexity of the language.
I also don't want beginners to feel too comfortable with sVB, to encourage to jump quickly to VB .NET.
So, you have can use workarounds, such as:
* Implement some sorting algorithm like the bubble sort, which actually is an educational experience I want kids and beginners to have before used to built-in frameworks. You can also put such implementation in a sVB code lib and reuse it. For more info about creating sVB libraries, see the How To section in the sVB reference book.
* You can also use VB .NET or C# to write a new lib for sVB, so that you can use the built-in Array.Sort method directly from the framework. See the sVB reference for more details.
* Add some prefix spaces to the control text to center it.
* Modify the form.xaml file to add the VerticalAlignment="Center" and HorizontalAlighnment="Center" attributes inside the control tag. But this change will be wiped out every time you save the changes made by the form designer.
* If you want to add this feature to all controls in the toolbox,  change the control template in the Bin\ToolBox\Controls folder inside the sVB installation folder.
* if you want a practical solution that allows you to change the control appearance beyond you can imagine, use the SetStyle and SetResourceDictionary methods (see the sVB refence).
This is actually why I didn't crowd the language with too many properties. You can actually do want you want using XAML styles, and I want to encourage devs to learn about this amazing design language so they can easily move to new technologies like WPF, WinUI, and MAUI.
By the way, Avalonia UI uses Xaml to run dotnet code on desktop, web and mobile with a single code base. One amazing things that happened last month, is that a developer used this to create a VB6 version that runs on Windows, Linux, Android and iOS!
https://github.com/BAndysc/AvaloniaVisualBasic6
You can actually use VB6 online here (not with complete features of course, but it is an open source project and who know where it can get in the future):
https://bandysc.github.io/AvaloniaVisualBasic6/?fbclid=IwY2xjawG1SU9leHRuA2FlbQIxMAABHd6Rh8V_6EfUIqSvgroWXhRLNkgeerDHrqhTr9xHN2yO146AcPIJL5bCIA_aem_dBvaCApfNKuAqPr1Cmyppg
Please, don't forget to close the issue if it is done.
Regards

________________________________
From: Drugo67 ***@***.***>
Sent: Thursday, November 28, 2024 8:29 AM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] sort question (Issue #94)


Hi Mohammad! Congratulations for the level 2 book. I think it is very useful! I wanted to ask 2 questions. One thing that I found useful in VB6 was to use the "Sort" member especially for Listboxes and ComboBoxes, and I wondered why it was not developed in sVB. And the second question is about the possibility of formatting a text in the center of a label. I see that there are many possibilities to change fonts, colors, etc... but there is no possibility to center it or format it on the left. How could I do it? thanks in advance and congratulations again

**Comment by Drugo67** [comment]
Thanks for your answer, Mohammad! I see your point of view. I had already seen the vb6 developed on avalonia a few days ago. great! I hope they develop it with more features.
Best Regard
Drugo
