### ISSUE TITLE
Mismatched keyboard key values. 

### ISSUE THREAD

**Issue by dynamicboy** [VBAndCs/sVB-Small-Visual-Basic#96]
When I press F10, the effect is the same as pressing the Alt key. I checked their values and found both are 156, whereas the value for F10 should be 99 because F9 is 98 and F11 is 100.

**Comment by VBAndCs** [comment]
F10 value is already 99
'''<summary>The F10 key.</summary>
<ReturnValueType(VariableType.Key)>
Public Shared ReadOnly Property F10 As Primitive = 99
And you can cjeck it out:
TW.WriteLine(Keys.F10)
The problem is that windows (for historical reasons) treats F10 as Alt, so it selectes the first menu on the menu bar!
I will search for a solution of this issue, but it is not a sVB in first place.

________________________________
From: dynamicboy ***@***.***>
Sent: Sunday, December 8, 2024 6:57 AM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Mismatched keyboard key values. (Issue #96)


When I press F10, the effect is the same as pressing the Alt key. I checked their values and found both are 156, whereas the value for F10 should be 99 because F9 is 98 and F11 is 100.

**Comment by VBAndCs** [comment]
I found a way to detect F10, and in sVB 3.1, your check for it will work. But note, that windows will still process it as Alt, so if you want to use F10 in another job in your program, don't forget to set the Event.Handled property to True to stop Windows from processing the F10 key any further.
clease close this issue.


________________________________
From: dynamicboy ***@***.***>
Sent: Sunday, December 8, 2024 6:57 AM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Mismatched keyboard key values. (Issue #96)


When I press F10, the effect is the same as pressing the Alt key. I checked their values and found both are 156, whereas the value for F10 should be 99 because F9 is 98 and F11 is 100.

**Comment by dynamicboy** [comment]
OK, thanks. I'm looking forward to using the sVB v3.1!
